### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by EarthlingDavey** [ministryofjustice/justice-gov-uk#116]
- [ ] Basic auth is working.
- [ ] Media Library uploads work.
- [ ] Document uploads work.
- [ ] Permalink settings are `/%postname%` - without trailing slash.
- [ ] Timezone: London
- [ ] Settings > Media - No date in documents permalink.
- [ ] Site health shows working scheduled tasks.
- [ ] Redirects are loaded via `wp safe-redirect-manager import public/app/themes/justice/301-redirects-news.csv` for each csv file.

**Comment by EarthlingDavey** [comment]
Closing as migration deployment is complete.
